// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'del': string;
  'media': string;
  'root': string;
  'time': string;
}
declare var cssExports: CssExports;
export = cssExports;
