// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'default': string;
  'info': string;
  'l': string;
  'm': string;
  's': string;
  'warning': string;
}
declare var cssExports: CssExports;
export = cssExports;
